/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing_sql_project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author arkaa
 */
public class Registration_form extends javax.swing.JFrame {
    
    String jimage_path = null;
    /**
     * Creates new form Registration_form
     */
    public Registration_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border j_textfield_borders = BorderFactory.createMatteBorder(1, 1, 1, 1 , Color.gray);
        jConfirmPasswordField.setBorder(j_textfield_borders);
        jFullname_TextField.setBorder(j_textfield_borders);
        jPhone_TextField.setBorder(j_textfield_borders);
        jUsername_TextField.setBorder(j_textfield_borders);
        jPasswordField.setBorder(j_textfield_borders);
        
        Border j_regiBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jPanel1.setBorder(j_regiBorder);
        jPanel2.setBorder(j_regiBorder);
        
//        Mouse enter and exit border object
        
        Border min_enter_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jFemale_RadioButton);
        bg.add(jMale_RadioButton);
    }
  
//  To verify if the fields are empty    
    public boolean verifyFields(){
        String fullname = jFullname_TextField.getText();
        String username = jUsername_TextField.getText();
        String phone = jPhone_TextField.getText();
        String pass = String.valueOf(jPasswordField.getPassword());
        String conpass = String.valueOf(jConfirmPasswordField.getPassword());
        
        if (fullname.equals("") || username.equals("") || phone.equals("") || pass.equals("") || conpass.equals("")){
            JOptionPane.showMessageDialog(null,"One or more fields empty");
            return false;
        }
        else if (!pass.equals(conpass)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
            return false;
        }
        
        else{return true;}
    }

//  To check if the username already exists in the database
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exists = false;
        
        String query = "SELECT * FROM users WHERE username = ?";
        
        try {
            st = MyConn.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if (rs.next()){
                username_exists = true;
                JOptionPane.showMessageDialog(null, "Username already exists");
            }
            } 
        
        catch (SQLException ex) {
            Logger.getLogger(Registration_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return username_exists;
        }
        
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRegistration_label = new javax.swing.JLabel();
        jMinimize_label = new javax.swing.JLabel();
        jClose_label = new javax.swing.JLabel();
        jName_label = new javax.swing.JLabel();
        jFullname_TextField = new javax.swing.JTextField();
        jUsername_Label = new javax.swing.JLabel();
        jPassword_Label = new javax.swing.JLabel();
        jConfirm_Password_Label = new javax.swing.JLabel();
        jUsername_TextField = new javax.swing.JTextField();
        jPhone_Label = new javax.swing.JLabel();
        jPhone_TextField = new javax.swing.JTextField();
        jGender_Label = new javax.swing.JLabel();
        jImage_Label = new javax.swing.JLabel();
        jMale_RadioButton = new javax.swing.JRadioButton();
        jFemale_RadioButton = new javax.swing.JRadioButton();
        jSelectimage_Button = new javax.swing.JButton();
        jImagepath_Label = new javax.swing.JLabel();
        jRegister_Button = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jConfirmPasswordField = new javax.swing.JPasswordField();
        jRegistertoLogin_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 150, 150));

        jRegistration_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRegistration_label.setText("Registration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jRegistration_label)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jRegistration_label)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMinimize_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jMinimize_label.setForeground(Color.lightGray);
        jMinimize_label.setText("-");
        jMinimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinimize_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinimize_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinimize_labelMouseExited(evt);
            }
        });

        jClose_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jClose_label.setForeground(Color.lightGray);
        jClose_label.setText("X");
        jClose_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClose_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jClose_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jClose_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jMinimize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jClose_label)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMinimize_label)
                            .addComponent(jClose_label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jName_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jName_label.setText("Full name");

        jFullname_TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jFullname_TextField.setForeground(new java.awt.Color(105, 105, 105));

        jUsername_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jUsername_Label.setText("Username");

        jPassword_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPassword_Label.setText("Password");

        jConfirm_Password_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jConfirm_Password_Label.setText("Confirm Password");

        jUsername_TextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPhone_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPhone_Label.setText("Phone");

        jPhone_TextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhone_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPhone_TextFieldKeyTyped(evt);
            }
        });

        jGender_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jGender_Label.setText("Gender");

        jImage_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jImage_Label.setText("Image");

        jMale_RadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMale_RadioButton.setText("Male");

        jFemale_RadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jFemale_RadioButton.setText("Female");

        jSelectimage_Button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSelectimage_Button.setText("select Image");
        jSelectimage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectimage_ButtonActionPerformed(evt);
            }
        });

        jImagepath_Label.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jImagepath_Label.setText("Image path");

        jRegister_Button.setBackground(new java.awt.Color(51, 0, 204));
        jRegister_Button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRegister_Button.setText("Register");
        jRegister_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegister_ButtonActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jConfirmPasswordField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jRegistertoLogin_Label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRegistertoLogin_Label.setForeground(new java.awt.Color(51, 0, 255));
        jRegistertoLogin_Label.setText("Already registered? Sign-in");
        jRegistertoLogin_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegistertoLogin_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRegistertoLogin_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRegistertoLogin_LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jName_label)
                    .addComponent(jPassword_Label)
                    .addComponent(jUsername_Label)
                    .addComponent(jConfirm_Password_Label)
                    .addComponent(jPhone_Label)
                    .addComponent(jGender_Label)
                    .addComponent(jImage_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRegister_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMale_RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFemale_RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addComponent(jFullname_TextField)
                    .addComponent(jUsername_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSelectimage_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jImagepath_Label))
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPhone_TextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRegistertoLogin_Label)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jName_label)
                    .addComponent(jFullname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsername_Label)
                    .addComponent(jUsername_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPassword_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jConfirm_Password_Label)
                    .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPhone_Label)
                    .addComponent(jPhone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGender_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jMale_RadioButton)
                        .addComponent(jFemale_RadioButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jImage_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSelectimage_Button)
                        .addComponent(jImagepath_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jRegister_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jRegistertoLogin_Label)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClose_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClose_labelMouseEntered
        // TODO add your handling code here:
//        Border close_enter_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED);
//        jClose_label.setBorder(close_enter_Border);
        jClose_label.setForeground(Color.RED);
    }//GEN-LAST:event_jClose_labelMouseEntered

    private void jClose_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClose_labelMouseExited
        // TODO add your handling code here:
//        Border close_exit_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray);
//        jClose_label.setBorder(close_exit_Border);
        jClose_label.setForeground(Color.lightGray);
    }//GEN-LAST:event_jClose_labelMouseExited

    private void jMinimize_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimize_labelMouseEntered
        // TODO add your handling code here:
//        Border min_enter_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
//        jMinimize_label.setBorder(min_enter_Border);
        jMinimize_label.setForeground(Color.black);
    }//GEN-LAST:event_jMinimize_labelMouseEntered

    private void jMinimize_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimize_labelMouseExited
        // TODO add your handling code here:
//        Border min_exit_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray);
//        jMinimize_label.setBorder(min_exit_Border);
        jMinimize_label.setForeground(Color.lightGray);
    }//GEN-LAST:event_jMinimize_labelMouseExited

    private void jClose_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClose_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jClose_labelMouseClicked

    private void jMinimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jMinimize_labelMouseClicked

    private void jPhone_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhone_TextFieldKeyTyped
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jPhone_TextFieldKeyTyped

    private void jSelectimage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectimage_ButtonActionPerformed
        // TODO add your handling code here:
        String path = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Images*","jpg","jpeg","png");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        if (filestate == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            jImagepath_Label.setText(path);
            
            jimage_path = path;
        }        
    }//GEN-LAST:event_jSelectimage_ButtonActionPerformed

    private void jRegister_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegister_ButtonActionPerformed
        // TODO add your handling code here:
        String fnameString = jFullname_TextField.getText();
        String usernameString = jUsername_TextField.getText();
        String passString = String.valueOf(jPasswordField.getPassword());
        String confirmpassString = String.valueOf(jConfirmPasswordField.getPassword());
        String phone = jPhone_TextField.getText();
        String gender = "Male";
        
        if (jFemale_RadioButton.isSelected()){
            gender = "Female";
        }
        
        if (verifyFields()){
            if(!checkUsername(usernameString)){
                PreparedStatement ps;
                ResultSet rs;
                String resgister_query = "INSERT INTO users(full_name, username, password, phone, gender, picture) VALUES (?,?,?,?,?,?)";
                
                try {
                    ps = MyConn.getConnection().prepareCall(resgister_query);
                    ps.setString(1, fnameString);
                    ps.setString(2, usernameString);
                    ps.setString(3, passString);
                    ps.setString(4, phone);
                    ps.setString(5, gender);
                    
                    try{
                        if (jimage_path!=null){
                            InputStream image = new FileInputStream(new File(jimage_path));
                            ps.setBlob(6,image);
                        }
                        else{
                            ps.setNull(6, java.sql.Types.NULL);
                        }
                        
                        
                        
                        if (ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Your account has been created");
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Check your information");
                        }
                    }
                    catch (FileNotFoundException | SQLException ex) {
                        Logger.getLogger(Registration_form.class.getName()).log(Level.SEVERE,null, ex);
                        
                    }
                    
                    
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jRegister_ButtonActionPerformed

    private void jRegistertoLogin_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistertoLogin_LabelMouseEntered
        // TODO add your handling code here:
        jRegistertoLogin_Label.setForeground(new Color(0,150,200));
    }//GEN-LAST:event_jRegistertoLogin_LabelMouseEntered

    private void jRegistertoLogin_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistertoLogin_LabelMouseExited
        // TODO add your handling code here:
        jRegistertoLogin_Label.setForeground(new Color(51,0,255));
    }//GEN-LAST:event_jRegistertoLogin_LabelMouseExited

    private void jRegistertoLogin_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistertoLogin_LabelMouseClicked
        // TODO add your handling code here:
        Login_form lf = new Login_form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRegistertoLogin_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jClose_label;
    private javax.swing.JPasswordField jConfirmPasswordField;
    private javax.swing.JLabel jConfirm_Password_Label;
    private javax.swing.JRadioButton jFemale_RadioButton;
    private javax.swing.JTextField jFullname_TextField;
    private javax.swing.JLabel jGender_Label;
    private javax.swing.JLabel jImage_Label;
    private javax.swing.JLabel jImagepath_Label;
    private javax.swing.JRadioButton jMale_RadioButton;
    private javax.swing.JLabel jMinimize_label;
    private javax.swing.JLabel jName_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPassword_Label;
    private javax.swing.JLabel jPhone_Label;
    private javax.swing.JTextField jPhone_TextField;
    private javax.swing.JButton jRegister_Button;
    private javax.swing.JLabel jRegistertoLogin_Label;
    private javax.swing.JLabel jRegistration_label;
    private javax.swing.JButton jSelectimage_Button;
    private javax.swing.JLabel jUsername_Label;
    private javax.swing.JTextField jUsername_TextField;
    // End of variables declaration//GEN-END:variables
}
